//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shizui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class BasicSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static BasicSetting defaultInstance = ((BasicSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BasicSetting())));
        
        public static BasicSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle PLAYER_CONFIGURATION_AREA {
            get {
                return ((global::System.Drawing.Rectangle)(this["PLAYER_CONFIGURATION_AREA"]));
            }
            set {
                this["PLAYER_CONFIGURATION_AREA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle TARGET_CONFIGURATION_AREA {
            get {
                return ((global::System.Drawing.Rectangle)(this["TARGET_CONFIGURATION_AREA"]));
            }
            set {
                this["TARGET_CONFIGURATION_AREA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string PLAYER_NICKNAME {
            get {
                return ((string)(this["PLAYER_NICKNAME"]));
            }
            set {
                this["PLAYER_NICKNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PLAYER_CP_ZONE {
            get {
                return ((int)(this["PLAYER_CP_ZONE"]));
            }
            set {
                this["PLAYER_CP_ZONE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PLAYER_HP_ZONE {
            get {
                return ((int)(this["PLAYER_HP_ZONE"]));
            }
            set {
                this["PLAYER_HP_ZONE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PLAYER_MP_ZONE {
            get {
                return ((int)(this["PLAYER_MP_ZONE"]));
            }
            set {
                this["PLAYER_MP_ZONE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int TARGET_HP_ZONE {
            get {
                return ((int)(this["TARGET_HP_ZONE"]));
            }
            set {
                this["TARGET_HP_ZONE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PLAYER_CP_BARSTART {
            get {
                return ((int)(this["PLAYER_CP_BARSTART"]));
            }
            set {
                this["PLAYER_CP_BARSTART"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PLAYER_HP_BARSTART {
            get {
                return ((int)(this["PLAYER_HP_BARSTART"]));
            }
            set {
                this["PLAYER_HP_BARSTART"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int PLAYER_MP_BARSTART {
            get {
                return ((int)(this["PLAYER_MP_BARSTART"]));
            }
            set {
                this["PLAYER_MP_BARSTART"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int TARGET_HP_BARSTART {
            get {
                return ((int)(this["TARGET_HP_BARSTART"]));
            }
            set {
                this["TARGET_HP_BARSTART"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AUTO_POT_ENABLED {
            get {
                return ((bool)(this["AUTO_POT_ENABLED"]));
            }
            set {
                this["AUTO_POT_ENABLED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AUTO_POT_PERCENTAGE {
            get {
                return ((int)(this["AUTO_POT_PERCENTAGE"]));
            }
            set {
                this["AUTO_POT_PERCENTAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RECOVER_MP_ENABLED {
            get {
                return ((bool)(this["RECOVER_MP_ENABLED"]));
            }
            set {
                this["RECOVER_MP_ENABLED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MP_SIT_PERCENTAGE {
            get {
                return ((int)(this["MP_SIT_PERCENTAGE"]));
            }
            set {
                this["MP_SIT_PERCENTAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MP_STAND_PERCENTAGE {
            get {
                return ((int)(this["MP_STAND_PERCENTAGE"]));
            }
            set {
                this["MP_STAND_PERCENTAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ALWAYS_ON_TOP {
            get {
                return ((bool)(this["ALWAYS_ON_TOP"]));
            }
            set {
                this["ALWAYS_ON_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AUTO_ATTACK {
            get {
                return ((bool)(this["AUTO_ATTACK"]));
            }
            set {
                this["AUTO_ATTACK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool USE_NEXT_TARGET {
            get {
                return ((bool)(this["USE_NEXT_TARGET"]));
            }
            set {
                this["USE_NEXT_TARGET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BOT_PAUSE_CP {
            get {
                return ((bool)(this["BOT_PAUSE_CP"]));
            }
            set {
                this["BOT_PAUSE_CP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int UPDATE_INTERVAL {
            get {
                return ((int)(this["UPDATE_INTERVAL"]));
            }
            set {
                this["UPDATE_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PLAYER_HP_BARSTART_INITIALIZED {
            get {
                return ((bool)(this["PLAYER_HP_BARSTART_INITIALIZED"]));
            }
            set {
                this["PLAYER_HP_BARSTART_INITIALIZED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PLAYER_CP_BARSTART_INITIALIZED {
            get {
                return ((bool)(this["PLAYER_CP_BARSTART_INITIALIZED"]));
            }
            set {
                this["PLAYER_CP_BARSTART_INITIALIZED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PLAYER_MP_BARSTART_INITIALIZED {
            get {
                return ((bool)(this["PLAYER_MP_BARSTART_INITIALIZED"]));
            }
            set {
                this["PLAYER_MP_BARSTART_INITIALIZED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TARGET_HP_BARSTART_INITIALIZED {
            get {
                return ((bool)(this["TARGET_HP_BARSTART_INITIALIZED"]));
            }
            set {
                this["TARGET_HP_BARSTART_INITIALIZED"] = value;
            }
        }
    }
}
